replicaCount: 3

metadata:
 name: loginsvc 
 label: loginsvc

image:
  name: loginsvc
  imageName: "icpdevcluster.icp:8500/default/login-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3003

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL


service:
  serviceMetadata:
    name: loginsvc
    labels:
      app: loginsvc
  selector:
    selectorName: loginsvc
  servicePortConfiguration:
    protocol: TCP
    name: loginsvc
    type: NodePort
    port: 3003
    targetPort: 3003
    nodePort: 30093