apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceMetadata.name }}
spec:
  type:  {{ .Values.service.servicePortConfiguration.type }}
  ports:
    - port: {{ .Values.service.servicePortConfiguration.port }}
      targetPort: {{ .Values.service.servicePortConfiguration.targetPort }}
  selector:
    app: {{ .Values.service.selector.selectorName }}