apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: {{ .Values.metadata.name }} 
spec:
 replicas: {{ .Values.replicaCount }}
 template:
   metadata:
     name: {{ .Values.metadata.name }} 
     labels:
       app: {{ .Values.metadata.label }} 
   spec:
     containers:
       - name: {{ .Values.image.name }} 
         image: {{ .Values.image.imageName }} 
         imagePullPolicy: {{ .Values.image.imagePullPolicy }} 
         env:
          - name: {{ .Values.envOfSecrets.envUID.name }} 
            valueFrom:
              secretKeyRef:
                name: {{ .Values.envOfSecrets.envUID.secretKeyRef.name }} 
                key: {{ .Values.envOfSecrets.envUID.secretKeyRef.key }} 
          - name: {{ .Values.envOfSecrets.envPASSWORD.name }} 
            valueFrom:
              secretKeyRef:
                name: {{ .Values.envOfSecrets.envPASSWORD.secretKeyRef.name }} 
                key: {{ .Values.envOfSecrets.envPASSWORD.secretKeyRef.key }} 
          - name: {{ .Values.envOfSecrets.envSECRET.name }} 
            valueFrom:
              secretKeyRef:
                name: {{ .Values.envOfSecrets.envSECRET.secretKeyRef.name }}
                key: {{ .Values.envOfSecrets.envSECRET.secretKeyRef.name }}
          - name: {{ .Values.envOfConfigmaps.envNODE_ENV.name }} 
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.envOfConfigmaps.envNODE_ENV.configMapKeyRef.name }}
                key: {{ .Values.envOfConfigmaps.envNODE_ENV.configMapKeyRef.key }}
          - name: {{ .Values.envOfConfigmaps.envDATABASE.name }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.envOfConfigmaps.envDATABASE.configMapKeyRef.name }}
                key: {{ .Values.envOfConfigmaps.envDATABASE.configMapKeyRef.key }}
          - name: {{ .Values.envOfConfigmaps.envPORT.name }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.envOfConfigmaps.envPORT.configMapKeyRef.name }}
                key: {{ .Values.envOfConfigmaps.envPORT.configMapKeyRef.key }}
          - name: {{ .Values.envOfConfigmaps.envHOSTNAME.name }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.envOfConfigmaps.envHOSTNAME.configMapKeyRef.name }}
                key: {{ .Values.envOfConfigmaps.envHOSTNAME.configMapKeyRef.key }}
          - name: {{ .Values.envOfConfigmaps.envPROTOCOL.name }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.envOfConfigmaps.envPROTOCOL.configMapKeyRef.name }}
                key: {{ .Values.envOfConfigmaps.envPROTOCOL.configMapKeyRef.key }}
         ports:
         - containerPort: {{ .Values.image.ports.containerPort }} 