apiVersion: v1
kind: Service
metadata:
  name: listingsvc
  labels:
    app: listingsvc
spec:
  ports:
  - port: 80
    targetPort: 7000
    name: http
  selector:
    app: listingsvc
---
# inside of the mesh, redirect "analyzer" to analyzer.svc.b.remote
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: listingsvc
spec:
  gateways:
  - mesh
  hosts:
  - listingsvc.default.svc.cluster.local
  http:
  - rewrite:
      # do the header re-write so we can ingress via host
      authority: listingsvc.svc.b.remote
    route:
    - destination:
        host: ingress.b.remote
        port:
          number: 80 ## app port number 
      weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-gatewaysvc
spec:
  gateways:
  - guestbook-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /gatewaysvc/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: gatewaysvc
