apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: odmsvc 
spec:
 replicas: 1
 template:
   metadata:
     name: odmsvc
     labels:
       app: odmsvc
   spec:
     containers:
       - name: odmsvc
         image: "mycluster.icp:8500/default/odm-microservice:latest" 
         imagePullPolicy: Always
         resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "128Mi"
         env:
          - name: ODM
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: ODM
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
         ports:
         - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
 name: odmsvc
 labels:
   app: odmsvc
spec:
 type: NodePort
 selector:
   app: odmsvc
 ports:
  - protocol: TCP
    name: odmsvc
    port: 3005
    targetPort: 3005
    nodePort: 30095
