replicaCount: 2

metadata:
 name: gatewaysvc 
 label: gatewaysvc
readinessProbe:
  path: /healthz
  port: 3016
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 15

livenessProbe:
  path: /healthz
  port: 3016
  initialDelaySeconds: 5
  timeoutSeconds: 1 
  periodSeconds: 15

hpa:
  metadata:
    name: gatewaymicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 1
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: gatewaysvc

image:
  name: gatewaysvc
  imageName: "s4saif/gateway-microservice:0.0.1" 
  imagePullPolicy: Always
  ports:
    containerPort: 3016
  requests:
    cpu: "60m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "200Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]

service:
  serviceMetadata:
    name: gatewaysvc
    labels:
      app: gatewaysvc
  selector:
    selectorName: gatewaysvc
  servicePortConfiguration:
    protocol: TCP
    name: gatewaysvc
    type: ClusterIP
    port: 3016
    targetPort: 3016