replicaCount: 1

metadata:
 name: angular 
 label: angular

hpa:
  metadata:
    name: frontendmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 1
  metrics:
    pods:
      targetAverageValue: 50
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: angular

image:
  name: angular
  imageName: "mycluster.icp:8500/default/angular:0.0.1" 
  imagePullPolicy: Always
  maxSurge: 1
  maxUnavailable: 0
  requests:
    cpu: "400m"
    memory: "800Mi"
  limits:
    cpu: "900m"
    memory: "1000Mi"


service:
  serviceMetadata:
    name: angular
  selector:
    selectorName: angular
  servicePortConfiguration:
    name: angular
    type: ClusterIP
    port: 80
    targetPort: 80
