# The IBM version of this configuration
version : 0.0.3

container-name-run : "listing-microservice-run"


host-path-run : .
host-path-tools : .

dockerfile-run : "Dockerfile"

image-name-run : "listing-microservice-run"

chart-path: "chart/listing-microservice"
deploy-target: "container"
deploy-image-target: "mycluster.icp:8500/default/email-microservice:0.0.1"