apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  UID: YWRtaW4=
  PASSWORD: YWRtaW4=
  UIDMARIADB: YWRtaW4=
  PASSWORDMARIADB: YWRtaW4=
  SECRET: aGVsbG8=
  EMAILUSERNAME: aWNwYWlyd2F5c0BnbWFpbC5jb20=
  EMAILPASSWORD: LmljcGFpcndheXM=
  MONGOUSERNAME: YWRtaW4=
  MONGOPASSWORD: YWRtaW4=
  